apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cat-dockerfile
spec:
  workspaces:
    - name: source
  steps:
    - name: cat-dockerfile
      image: 'zshusers/zsh:4.3.15'
      resources: {}
      script: |
        #!/usr/bin/env zsh
        cat $(workspaces.source.path)/Dockerfile
